### ISSUE TITLE
lein can't connect to the Lingy::nREPL server

### ISSUE THREAD

**Issue by ingydotnet** [lingy-lang/lingy#53]
```
-->: :op eval, :client 1
buffer: '287: d4:code174:(clojure.core/binding [clojure.core/*ns* (clojure.core/or (clojure.core/find-ns (clojure.core/symbol "reply.eval-modes.nrepl")) clojure.core/*ns*)] (set! *print-length* nil))2:id36:097d0ee0-96c9-4e09-bdfb-ee2c7df73a592:op4:eval7:session36:8C9D86CA-2BF5-11EE-9DC0-D6F304E77F02e'
request:
  code: (clojure.core/binding [clojure.core/*ns* (clojure.core/or (clojure.core/find-ns (clojure.core/symbol "reply.eval-modes.nrepl")) clojure.core/*ns*)] (set! *print-length* nil))
  id: 097d0ee0-96c9-4e09-bdfb-ee2c7df73a59
  op: eval
  session: 8C9D86CA-2BF5-11EE-9DC0-D6F304E77F02

<--: :op eval, :client 1
response:
  err: |
    Lingy Error: No such namespace: 'clojure.core'
  id: 097d0ee0-96c9-4e09-bdfb-ee2c7df73a59
  session: 8C9D86CA-2BF5-11EE-9DC0-D6F304E77F02

<--: :op eval, :client 1
response:
  id: 097d0ee0-96c9-4e09-bdfb-ee2c7df73a59
  session: 8C9D86CA-2BF5-11EE-9DC0-D6F304E77F02
  status: done
```
